base_url = "https://jamiebrynes.com"
compile_sass = true
highlight_code = true
highlight_theme = "ayu-dark"
build_search_index = true

title = "Jamie Brynes - software engineer"

taxonomies = [
    {name = "tags", paginate_by = 5}
]

[extra]
# Put all your custom variables here
github = "https://www.github.com/jamiebrynes7"
twitter = "https://www.twitter.com/jamiebrynes"
instagram = "https://www.instagram.com/jamiebrynes7"
linkedin = "https://www.linkedin.com/in/jamiesonbrynes"
email = "jamiebrynes7@gmail.com"