baseURL: https://jamiebrynes.com
languageCode: en-us
title: Jamie Brynes
taxonomies:
  tag: tags

menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
    - name: Writing
      pageRef: /posts
      weight: 2
    - name: Projects
      pageRef: /projects
      weight: 3

params:
  socials:
    - title: GitHub
      icon: github
      url: https://www.github.com/jamiebrynes7
    - title: Bluesky
      icon: bsky
      url: https://bsky.app/profile/jamiebrynes.com
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/jamiesonbrynes/

markup:
  highlight:
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
