baseURL: https://jamiebrynes.com
languageCode: en-us
title: Jamie Brynes
taxonomies:
  tag: tags

menu:
  main:
    - name: Writing
      url: /posts
      weight: 1
    - name: Projects
      url: /projects
      weight: 2

params:
  socials:
    - title: GitHub
      icon: github
      url: https://www.github.com/jamiebrynes7
    - title: Twitter
      icon: twitter
      url: https://www.twitter.com/jamiebrynes
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/jamiesonbrynes/

markup:
  highlight:
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
