baseURL: https://jamiebrynes.com
languageCode: en-us
title: Jamie Brynes

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writing
      url: /posts
      weight: 2
    - name: Projects
      url: /projects
      weight: 3

params:
  socials:
    - icon: github
      url: https://www.github.com/jamiebrynes7
    - icon: twitter
      url: https://www.twitter.com/jamiebrynes
    - icon: linkedin
      url: https://www.linkedin.com/in/jamiesonbrynes/
