version: '2.1'

jobs:
  build-and-deploy:
    docker:
      - image: 154290596490.dkr.ecr.us-east-1.amazonaws.com/jamiebrynes.com:latest
    resource_class: small

    steps:
      - checkout
      - run:
          name: install deps
          command: |
            npm ci
      - run:
          name: build css
          command: |
            npm run build
      - run:
          name: build site
          command: |
            hugo --minify
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              npx netlify deploy --dir ./public --site optimistic-edison-23360f
            else 
              npx netlify deploy --dir ./public --site optimistic-edison-23360f --prod
            fi

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context:
            - aws-ecr-reader
            - netlify-cli

