name: Build 
on: [push]

jobs:
  build:
    name: Build Rust binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-rust-musl
      - uses: actions/upload-artifact@master
        with:
          name: kudos-please-binary
          path: /github/workspace/release