name: Check blog posts
on: [push]

jobs:
  spell-check: 
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/spellcheck

  build-website:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/zola