name: Publish Kudos Please
on: 
  push:
    branches:
      - master

jobs:
  publish:
    name: "Publish Kudos Please"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-rust-musl
      - uses: actions/upload-artifact@master
        with:
          name: kudos-please-binary
          path: release
